
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pablo
 */
public class frmVenta extends javax.swing.JFrame {

    /**
     * Creates new form frmVenta
     */
    public frmVenta() {
        initComponents();
        setCmbSesiones("");
      
    }
    
    
    public void setCmbSesiones(String condicion){
        Query query = new Query();
        String[] columnas = {"Tour","fecha","precio","disponibilad","Ubicacion","Guia"};
        DefaultTableModel model =  new DefaultTableModel(null,columnas);
        try{
            ResultSet lista= query.select("*","tour"," INNER JOIN sesion ON sesion.idTour= tour.idTour INNER JOIN guia ON guia.idGuia = sesion.idGuia"
                    + " WHERE sesion.deleted_at is Null  AND tour.deleted_at is NULL AND guia.deleted_at is NULL"+condicion);
            while(lista.next()){
                model.addRow(new Object[]{lista.getString("tour.nombre"),lista.getString("fecha"),lista.getString("precio"),lista.getString("disponibilidad"),lista.getString("ubicacion"),lista.getString("guia.nombre")});

            }
        }catch(Exception e){
            
        }
        tbl.setModel(model); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        lblTitulo3 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblTitulo4 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        lblTitulo5 = new javax.swing.JLabel();
        lblTitulo6 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        spnEntradas = new javax.swing.JSpinner();
        lblTitulo7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        txtNombreTour = new javax.swing.JTextField();
        lblNombreTour = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        lblNombre2 = new javax.swing.JLabel();
        lblNombre3 = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreGuia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTelefonoGuia = new javax.swing.JTextField();
        lblTitulo8 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        lblTitulo1.setText("Venta");
        jPanel1.add(lblTitulo1);
        lblTitulo1.setBounds(364, 30, 74, 23);

        lblTitulo2.setText("Datos Cliente");
        jPanel1.add(lblTitulo2);
        lblTitulo2.setBounds(32, 297, 89, 23);
        jPanel1.add(txtNombreCliente);
        txtNombreCliente.setBounds(109, 331, 287, 31);

        lblTitulo3.setText("Telefono :");
        jPanel1.add(lblTitulo3);
        lblTitulo3.setBounds(25, 370, 74, 23);
        jPanel1.add(txtTelefono);
        txtTelefono.setBounds(109, 366, 134, 31);

        lblTitulo4.setText("Rut :");
        jPanel1.add(lblTitulo4);
        lblTitulo4.setBounds(30, 410, 74, 23);
        jPanel1.add(txtRut);
        txtRut.setBounds(110, 400, 134, 31);

        lblTitulo5.setText("Datos Sesion");
        jPanel1.add(lblTitulo5);
        lblTitulo5.setBounds(470, 300, 74, 23);

        lblTitulo6.setText("Nombre :");
        jPanel1.add(lblTitulo6);
        lblTitulo6.setBounds(25, 335, 74, 23);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver);
        btnVolver.setBounds(200, 610, 63, 23);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar);
        btnAceptar.setBounds(90, 610, 71, 23);

        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(925, 331, 200, 74);

        spnEntradas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                spnEntradasMouseMoved(evt);
            }
        });
        spnEntradas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                spnEntradasMouseEntered(evt);
            }
        });
        jPanel1.add(spnEntradas);
        spnEntradas.setBounds(110, 440, 61, 31);

        lblTitulo7.setText("Entradas :");
        jPanel1.add(lblTitulo7);
        lblTitulo7.setBounds(30, 450, 74, 23);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(50, 60, 806, 220);

        txtNombreTour.setEditable(false);
        jPanel1.add(txtNombreTour);
        txtNombreTour.setBounds(490, 380, 290, 30);

        lblNombreTour.setText("Nombre :");
        jPanel1.add(lblNombreTour);
        lblNombreTour.setBounds(430, 380, 50, 20);

        lblNombre1.setText("Precio :");
        jPanel1.add(lblNombre1);
        lblNombre1.setBounds(430, 420, 50, 20);

        txtPrecio.setEditable(false);
        jPanel1.add(txtPrecio);
        txtPrecio.setBounds(490, 420, 220, 30);

        txtDuracion.setEditable(false);
        jPanel1.add(txtDuracion);
        txtDuracion.setBounds(490, 500, 130, 30);

        lblNombre2.setText("Duración :");
        jPanel1.add(lblNombre2);
        lblNombre2.setBounds(430, 510, 49, 14);

        lblNombre3.setText("Ubicación :");
        jPanel1.add(lblNombre3);
        lblNombre3.setBounds(430, 460, 60, 20);

        txtUbicacion.setEditable(false);
        jPanel1.add(txtUbicacion);
        txtUbicacion.setBounds(490, 460, 230, 30);

        txtFecha.setEditable(false);
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        jPanel1.add(txtFecha);
        txtFecha.setBounds(490, 330, 130, 30);

        jLabel3.setText("Fecha:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(430, 340, 33, 14);

        jLabel1.setText("Nombre :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(430, 580, 60, 20);

        txtNombreGuia.setEditable(false);
        jPanel1.add(txtNombreGuia);
        txtNombreGuia.setBounds(490, 580, 220, 30);

        jLabel2.setText("Telefono :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(430, 620, 70, 30);

        txtTelefonoGuia.setEditable(false);
        txtTelefonoGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoGuiaActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefonoGuia);
        txtTelefonoGuia.setBounds(490, 620, 230, 30);

        lblTitulo8.setText("Datos Guia");
        jPanel1.add(lblTitulo8);
        lblTitulo8.setBounds(480, 550, 74, 23);

        lblTotal.setText("Total :");
        jPanel1.add(lblTotal);
        lblTotal.setBounds(30, 500, 50, 20);

        txtTotal.setEditable(false);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotal);
        txtTotal.setBounds(110, 500, 220, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefonoGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoGuiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoGuiaActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        String nomTour ="" ,fecha="";
        fecha = tbl.getValueAt(tbl.getSelectedRow(), 1).toString();
        nomTour = tbl.getValueAt(tbl.getSelectedRow(), 0).toString();
        
        Query q = new Query();
        ResultSet lista;
        try{
            lista = q.select("*","tour"," INNER JOIN sesion ON sesion.idTour= tour.idTour INNER JOIN guia ON guia.idGuia = sesion.idGuia"
                    + " WHERE sesion.deleted_at is Null  AND tour.deleted_at is NULL AND guia.deleted_at is NULL AND tour.nombre='"+nomTour+"' AND sesion.fecha='"+fecha+"'");
            txtNombreTour.setText(nomTour);
            txtFecha.setText(fecha);
            if(lista.next()){
                txtDuracion.setText(lista.getString("tour.duracion"));
                txtNombreGuia.setText(lista.getString("guia.nombre"));
                txtUbicacion.setText(lista.getString("ubicacion"));
                txtTelefonoGuia.setText(lista.getString("telefono"));
                txtPrecio.setText(lista.getString("precio"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e, "", 2);
        }
    }//GEN-LAST:event_tblMouseClicked

    private void spnEntradasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spnEntradasMouseEntered

    }//GEN-LAST:event_spnEntradasMouseEntered

    private void spnEntradasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spnEntradasMouseMoved

    }//GEN-LAST:event_spnEntradasMouseMoved

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
       
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked

    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved

    }//GEN-LAST:event_jPanel2MouseMoved

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        frmMenu menu = new frmMenu();
        this.dispose();
        menu.pack();
        menu.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JLabel lblNombreTour;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblTitulo4;
    private javax.swing.JLabel lblTitulo5;
    private javax.swing.JLabel lblTitulo6;
    private javax.swing.JLabel lblTitulo7;
    private javax.swing.JLabel lblTitulo8;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JSpinner spnEntradas;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreGuia;
    private javax.swing.JTextField txtNombreTour;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoGuia;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
